-- Cortex Space Weapons
-- Space Expansion V2.9
-- Authors: RandomGuy
-- https://github.com/nuttyb-community/nuttyb

{
corocan = {
weapondefs = {
Orbital_3Cannon = {
				areaofeffect = 200,
				avoidfeature = false,
				avoidfriendly = false, 
				burst = 3,
				burstrate= 0.1,
				cegtag = "arty-extraheavy",
				craterareaofeffect = 300,
				collidefriendly = false,
				collidefeature = false,
				canattackground = true,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-large",
				firestarter = 10,
				impulsefactor = 0.2,
				name = "Orbital Bombardment",
				tolerance = 50000,
				noselfdamage = true,
				range = 100,
				reloadtime = 11,
				soundhit = "xplonuk5",
				soundhitwet = "splslrg",
				soundstart = "KroGun1",
				sprayangle = 500,
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 200,
					commanders = 66.6,
					shields = 40,
				},
			},
},
		weapons = {
			[1] = {
				def = "ORBITAL_3CANNON",
				maindir = "0 -1 0",
				onlytargetcategory = "SURFACE",
			},
		},
},
corobruiser = {
weapondefs = {
Inquisitor_Missiles = {
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 25,
				avoidfeature = false,
				avoidfriendly = false,
				burst = 2,
				burstrate = 0.2,
				burnblow = false,
				canattackground = false,
				cegtag = "missiletrailviper",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				edgeeffectiveness = 0.15,
				energypershot = 0,
				explosiongenerator = "custom:genericshellexplosion-tiny-aa",
				firestarter = 72,
				flighttime = 2,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "cormissile3fast.s3o",
				name = "Orbital Striker Missiles.",
				noselfdamage = true,
				range = 800,
				reloadtime = 1,
				smoketrail = true,
				smokePeriod = 5,
				smoketime = 12,
				smokesize = 4.8,
				smokecolor = 0.95,
				smokeTrailCastShadow = false,
				castshadow = false, --projectile
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				soundtrigger = true,
				startvelocity = 200,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 9950,
				tracks = true,
				turnrate = 68000,
				turret = true,
				weaponacceleration = 1000,
				weapontype = "MissileLauncher",
				weaponvelocity = 1500,
				cylindertargeting = 0.4,
				damage = {
					default = 85,
				},
			},
},
		weapons = {
			[1] = {
				def = "INQUISITOR_MISSILES",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
maxangledif = 360,
			},
[2] = {
				def = "INQUISITOR_MISSILES",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
maxangledif = 360
			},
		},
},
coroheavy = {
weapondefs = {
			Heavy_Laser = {
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				avoidneutral = false,
				collideneutral = false,
				areaofeffect = 30,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.15,
				corethickness = 1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.2,
				energypershot = 50,
				explosiongenerator = "custom:laserhit-medium-red",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0.1,
				laserflaresize = 10,
				name = "High energy space laser",
				noselfdamage = true,
				range = 1100,
				reloadtime = 1.2,
				rgbcolor = "1 0 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 3.4,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 80,
				damage = {
					default = 220,
				},
			},
		},
		weapons = {
			[1] = {
				def = "HEAVY_LASER",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
[2] = {
				def = "HEAVY_LASER",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
cororocket = {
weapondefs = {
			madsam_missile = {
				burst = 3,
				burstrate = 0.2,
				areaofeffect = 5,
				avoidfriendly = false,
				alwaysvisible = true,      
				collidefeature = false,
				collidefriendly = false,
				cylindertargeting = 1,
				energypershot = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium",
				flighttime = 2,
				name = "Orbital Rocket Defense System",
				tolerance = 65536,
				range = 1000,
				reloadtime = 1.5,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 4,
				smoketime = 60,
				smoketrail = true,
				weaponacceleration = 1000,
				weapontimer = 1,
				weaponvelocity = 2000,
				damage = {
					default = 93.3333,
				},
			},
		},
		weapons = {
			[1] = {
				def = "MADSAM_MISSILE",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
corocannon = {
weapondefs = {
			Juno = {
				areaofeffect = 300,
				alwaysvisible = true,
				flighttime = 6,
				cegtag = "genericshellexplosion-small-lightning",
				canattackground = false,
				collidefeature = false,
				collidefriendly = false,
				edgeeffectiveness = 0.5,
				impulsefactor = 2,
				name = "Unstable Anti-Orbital Plasma Sphere",
				model = "",
				range = 1350,
				reloadtime = 9.2,
				tolerance = 5000,
				tracks = true,
				turnRate = 32000,
				soundhit = "xplosml5",
				soundhitwet = "lightning",
				soundstart = "lghthvy1",
				weapontype = "StarburstLauncher",
				explosiongenerator = "custom:genericshellexplosion-huge-lightning",
				startVelocity = 1500,
				weaponvelocity = 1500,
				weaponTimer = 1,
				damage = {
					default = 1,
					space = 3500,
				},
			},
		},
		weapons = {
			[1] = {
				def = "JUNO",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
coroapoc = {
weapondefs = {
			apocalypse = {
				areaofeffect = 500,
				avoidfeature = false,
				alwaysvisible = true,
				burst = 11,
				burstrate = 0.4,
				collidefriendly = false,
				craterareaofeffect = 500,
				craterboost = 1,
				cratermult = 1,
				cegtag = "meteortrail",
				canattackground = true,
				collidefeature = false,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-meteor",
				impulsefactor = 2,
				name = "Meteor Rain",
				noselfdamage = true,
				range = 1700,
				reloadtime = 33,
				tolerance = 4000,
				size = 10,
				soundhit = "xplonuk4",
				startvelocity = 400,
				soundhitwet = "sizzle",
				sprayangle = 900,
				turret = true,
				weapontype = "Cannon",
				weaponacceleration = 600,
				weaponvelocity = 400,
				hightrajectory = 1,
				proximitypriority = -1,
				heightBoostFactor = 0.5,
				damage = {
					default = 2200,
					shields = 1100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[2] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[3] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[4] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[5] = {
				def = "",
			},
			[6] = {
				def = "",
			},
		},
},
legofighter = {
weapondefs = {
			lightlaser = {
				canattackground = false,
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "0.05 1 0.05",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 100,
				damage = {
					default = 17.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legocan = {
weapondefs = {
			Orbital_LightningCannon = {
				areaofeffect = 250,
				avoidfeature = false,
				avoidfriendly = false,      
				craterareaofeffect = 0,
				canattackground = true,
				collidefeature = false,
				collidefriendly = false,
				cegtag = "lightning_stormbolt",
				energypershot = 30,
				edgeeffectiveness = 0.6,
				explosiongenerator = "custom:genericshellexplosion-medium-lightning",
				firestarter = 10,
				flighttime = 12,
				gravityaffected = "false",
				impulsefactor = 0.4,
				name = "Orbital Lightning Cannon",
				tolerance = 65536,
				noselfdamage = true,
				range = 300,
				cylinderTargeting = 10,
				heightMod = 0.1,
				reloadtime = 12,
				model = "",
				soundhit = "lashit",
				soundhitwet = "sizzle",
				soundstart = "lghthvy1",
				startvelocity = 400,
				turret = true,
				tracks = true,
				tolerance = 60000,
				turnrate = 400,
				weaponacceleration = 400,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 400,
				interceptedByShieldType = 1,
				customparams = {
					cluster_def = 'zap',
					cluster_number = 10,
					exclude_preaim = true,
					smart_priority = true,
				},
				damage = {
					default = 300,
					commanders = 100,
					shields = 60,
				},
			},
			zap = {
				areaofeffect = 100,
				avoidfeature = false,
				cegtag = "lightning_stormbolt_small",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:plasmahit-sparkonly",
				gravityaffected = "true",
				impulsefactor = 0.3,
				name = "Lightning Discharge",
				noselfdamage = true,
				range = 30,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "lashit",
				soundhitwet = "sizzle",
				soundstart = "",
				weapontype = "Cannon",
				damage = {
					default = 50,
					commanders = 20,
					shields = 20,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_LIGHTNINGCANNON",
				maindir = "0 -1 0",
				maxangledif = 360,
				onlytargetcategory = "NOTAIR",
				weaponAimAdjustPriority = nil,
				fastAutoRetargeting = false,
			},
		},
},
legspace = {
buildoptions = {
"legoc",
"legosat",
"legofighter",
"legocan",
"legosolar",
"legobruiser",
"legotrigun",
},
},
legspacet3 = {
buildoptions = {
"legoc",
"legobomber",
"legospy",
"legofort",
"legohelios",
},
},
}