-- Legion Space Weapons
-- Space Expansion V2.9
-- Authors: RandomGuy
-- https://github.com/nuttyb-community/nuttyb

{
legobruiser = {
weapondefs = {
			velgun = {
 				predictBoost = 0.3,
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 15,
				avoidfeature = false,
				avoidfriendly = false,
				avoidneutral = false,
				collideneutral = false,
				burst = 6,
				burstrate = 0.09,
				burnblow = false,
				canattackground = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.038,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulsefactor = 0.5,
				intensity = 0.8,
				name = "Rapid-fire machine gun",
				noselfdamage = true,
				proximitypriority = 1,
				range = 540,
				reloadtime = 0.45,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun2",
				soundstartvolume = 5.0,
				thickness = 0.91,
				tolerance = 60000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 916,
				cylindertargeting = 0.5,
				damage = {
					default = 18,
				},
			},
		},
		weapons = {
			[1] = {
				def = "velgun",
				maindir = "0 0 1",
				maxangledif = 360,
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legotrigun = {
weapondefs = {
			Longinus_Missile = {
				fixedLauncher = true,
				areaofeffect = 30,
				avoidfeature = false,
				avoidfriendly = false,      
				craterareaofeffect = 0,
				canattackground = false,
				collidefeature = false,
				collidefriendly = false,
				cegtag = "starfire_arty",
				energypershot = 30,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:ministarfire-explosion",
				firestarter = 10,
				flighttime = 5,
				gravityaffected = "false",
				impulsefactor = 0.4,
				name = "Longinus Missile",
				tolerance = 65536,
				noselfdamage = true,
				range = 1200,
				reloadtime = 7,
				model = "",
				soundhit = "xplomed2",
				soundhitwet = "splsmed",
				soundstart = "cannhvy5",
				startvelocity = 450,
				turret = true,
				tracks = true,
				tolerance = 60000,
				turnrate = 30000,
				weaponacceleration = 450,
				weapontype = "StarburstLauncher",
				weaponvelocity = 700,
				cylindertargeting = 0.32,
				damage = {
					default = 1540,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LONGINUS_MISSILE",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
			[2] = {
				def = "",
			},
		},
},
legospy = {
weapondefs = {
			spygun = {
				accuracy = 100,
				collidefriendly = false,
				collideenemy = false,
				collidefeature = false,
				accuracy = 0,
				areaofeffect = 1,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "arty-botrail",
				collidefriendly = false,
				edgeeffectiveness = 0,
				explosiongenerator = "custom:botrailspawn",
				gravityaffected = "true",
				heightboostfactor = 0,
				hightrajectory = 0,
				impulsefactor = 0.5,
				leadbonus = 0,
				energypershot = 850,
				metalpershot = 32,
				model = "Units/legeyes.s3o",
				mygravity = 0.22,
				name = "SpyCannon",
				noselfdamage = true,
				range = 1000,
				reloadtime = 6,
				soundhit = "xplonuk1xs",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundstartvolume = 30,
				sprayangle = 2000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1250,
				customparams = {
					spawns_name = "legoeyes",
					spawns_surface = "LAND SEA",
				},
				damage = {
					default = 1,
				},
},
},
weapons = {
			[1] = {
				def = "SPYGUN",
				onlytargetcategory = "SURFACE",

			},
[2] = {
				def = "SPYGUN",
				onlytargetcategory = "SURFACE",

			},
[3] = {
				def = "SPYGUN",
				onlytargetcategory = "SURFACE",

			},
		},
},
legohelios = {
weapondefs = {
			t3heatray = {
				areaofeffect = 800,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				beamtime = 5,
				camerashake = 0.1,
				corethickness = 5,
				craterareaofeffect = 100,
				craterboost = 0,
				cratermult = 0,
				canattackground = true,
				cylindertargeting = 50,
				edgeeffectiveness = 0.45,
				energypershot = 5000,
				explosiongenerator = "custom:heatray-huge",
				firestarter = 90,
				impulsefactor = 0,
				laserflaresize = 10,
				minIntensity = 1,
				name = "Perfect Orbital Heatray",
				noselfdamage = true,
				range = 500,
				reloadtime = 15,
				rgbcolor = "1 0.5 0",
				rgbcolor2 = "0.9 1.0 0.5",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heatray3",
				soundstartvolume = 38,
				soundtrigger = 1,
				thickness = 10,
				turret = true,
				tolerance = 65536,
				weapontype = "BeamLaser",
				weaponvelocity = 2100,
				heightmod = 0.1,
				damage = {
					default = 50000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "t3heatray",
				maindir = "0 -1 0",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
		},
},
legocannon = {
weapondefs = {
					railgunt3 = {
				predictboost = 0.2,
				areaofeffect = 150,
				avoidfeature = false,
				collidefeature = false,
				collideneutral = false,
				avoidneutral = false,
				burnblow = false,
				canattackground = false,
				cegtag = "railgun",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.12,
				edgeeffectiveness = 0.85,
				energypershot = 800,
				explosiongenerator = "custom:genericshellexplosion-large-aa-purple",
				firestarter = 0,
				impulsefactor = 2,
				intensity = 1.0,
				name = "Heavy Anti-Orbital Railgun",
				noselfdamage = true,
				range = 1450,
				reloadtime = 8,
				rgbcolor = "1 0.33 0.7",
				soundhit = "impact",
				soundhitwet = "splshbig",
				soundstart = "railgun3",
				soundstartvolume = 80,
				thickness = 4,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 7000,
				damage = {
					default = 2900,
				},
			},
		},
		weapons = {
			[1] = {
				def = "railgunt3",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legolaser = {
weapondefs = {
Orbital_Beamer = {
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				burnblow = false,
				beamdecay = 0.05,
				beamtime = 0.1,
				beamttl = 1,
				corethickness = 0.233,
				gravityaffected = "false",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				cylindertargeting = 128,
				edgeeffectiveness = 1,
				energypershot = 2,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 9.35,
				name = "Anti Orbital Laser",
				noselfdamage = true,
				range = 1000,
				reloadtime = 0.1,
				rgbcolor = "0.1 1 0.1",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "beamershot2",
				soundtrigger = 1,
				thickness = 2.4,
				tolerance = 65000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 3500,
				weapontimer = 4,
				minIntensity = 1,
				heightmod = 0.1,
				damage = {
					default = 19,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_BEAMER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
armolaser = {
weapondefs = {
			orbital_laser = {
				accuracy = 0,
				areaofeffect = 10,
				avoidfriendly = false,
				avoidfeature = false,
				alwaysvisible = true,
				burnblow = false,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				cylindertargeting = 5,
				duration = 0.1,
				edgeeffectiveness = 1,
				energypershot = 1,
				explosiongenerator = "custom:genericshellexplosion-small",
				gravityaffected = "false",
				stages = 0,
				impulsefactor = 0,
				intensity = 5,
				name = "Orbital Defense Laser",
				noselfdamage = true,
				range = 1000,
				reloadtime = 0.2,
				rgbcolor = "0 0 1",
				predictboost = 1,
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				thickness = 5,
				tolerance = 65535,
				turret = true,
				weapontimer = 3,
				weapontype = "LaserCannon",
				weaponvelocity = 1500,
				heightmod = 0.1,
				damage = {
					default = 39,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_LASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
armobomber = {
weapondefs = {
			arm_botrail = {
				accuracy = 0,
				areaofeffect = 0.2,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "arty-botrail",
				collidefriendly = false,
				craterareaofeffect = 116,
				craterboost = 0.1,
				cratermult = 0.1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:botrailspawn",
				gravityaffected = "true",
				heightboostfactor = 0,
				hightrajectory = 0,
				impulsefactor = 0.5,
				leadbonus = 0,
				energypershot = 5900,
				metalpershot = 65,
				model = "Units/ARMVADER.s3o",
				mygravity = 0.22,
				name = "Tumbleweed Cannon",
				noselfdamage = true,
				range = 900,
				reloadtime = 1,
				stockpile = true,
				stockpiletime = 6,
				soundhit = "xplonuk1xs",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundstartvolume = 50,
				sprayangle = 600,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1250,
				customparams = {
					spawns_name = "armvader",
					spawns_surface = "LAND",
					stockpilelimit = 10,
				},
				damage = {
					default = 1000,
					commanders = 500,
					shields = 500,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARM_BOTRAIL",
				maindir = "0 -1 0",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
[2] = {
def = "",
},
[3] = {
def = "",
},
[4] = {
def = "",
},
[5] = {
def = "",
},
		},
},
}