-- Space Unique Weapons
-- Space Expansion V2.9
-- Authors: RandomGuy
-- https://github.com/nuttyb-community/nuttyb

{
corobomber = {
weapondefs = {
cannon = {
				burst = 3,
				burstrate = 0.2,
				alwaysvisible = true,
				collidefriendly = false,
				collidefeature = false,
				avoidfriendly = false,
				canattackground = true,
				areaofeffect = 100,
				heightboostfactor = 0,
				cegtag = "missiletrailmship",
				craterareaofeffect = 100,
				edgeeffectiveness = 0.7,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				interceptedbyshieldtype = 1,
				name = "Orbital Bombardment Battery.",
				proximitypriority = 1,
				range = 900,
				reloadtime = 4,
				smoketrail = false,
				weapontype = "Cannon",
				weaponvelocity = 500,
				soundhit = "lrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot2",
				soundhitvolume = 19,
				soundstartvolume = 12,
				soundtrigger = true,
				turret = true,
				damage = {
					default = 500,
					commanders = 166.6,
				},
			},
			heavy_cannon = {
				areaofeffect = 200,
				alwaysvisible = true,
				canattackground = true,
				collidefriendly = false,
				collidefeature = false,
				name = "Heavy long-range orbital payload cannon.",
				explosiongenerator = "custom:genericshellexplosion-huge-bomb",
				range = 900,
				size = 10,
				reloadtime = 7,
				weaponvelocity = 400,
				heightboostfactor = 0,
				edgeeffectiveness = 0.3,
				hightrajectory = 1,
				impulsefactor = 0.5,
				weapontype = "Cannon",
				tolerance = 4000,
				turret = true,
				soundhit = "lrpcexplo",
				soundhitvolume = 20,
				soundhitwet = "splshbig",
				soundstart = "lrpcshot",
				damage = {
					default = 2500,
					shields = 1250,
					commanders = 1000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "HEAVY_CANNON",
				maindir = "0 0.5 1",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "CANNON",
				onlytargetcategory = "SURFACE",
			},
		},
},
legofort = {
		weapondefs = {
			semiauto = {
				collidefriendly = false,
				collidefeature = false,
				accuracy = 1,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				beamburst = true,
				beamdecay = 1,
				beamtime = 0.07,
				burst = 6,
				burstrate = 0.06667,
				canattackground = false,
				corethickness = 0.35,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 10,
				impulsefactor = 0,
				largebeamlaser = true,
				laserflaresize = 8.8,
				name = "Rapid-fire close quarters orbital 2 orbital laser",
				noselfdamage = true,
				proximitypriority = 1,
				pulsespeed = 8,
				range = 1050,
				reloadtime = 0.63333,
				rgbcolor = "0 0.75 0",
				rgbcolor2 = "0.9 0.9 0.6",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasfirerc",
				soundtrigger = 1,
				targetborder = 0.2,
				thickness = 2.4,
				tolerance = 30000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 920,
				damage = {
					default = 21.111,
				},
			},
			Omissiles = {
				proximitypriority = -1,
				avoidfriendly = false,
				areaofeffect = 60,
				avoidfeature = false,
				collidefriendly = false,
				collidefeature = false,
				burnblow = true,
				canattackground = false,
				cegtag = "missiletrailaa",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 72,
				fixedLauncher = true,
				flighttime = 7.5,
				impulsefactor = 0.123,
				model = "leglargerocket.s3o",
				name = "Advanced o2o missile launcher",
				noselfdamage = true,
				range = 1050,
				reloadtime = 6,
				smoketrail = true,
				smokePeriod = 5,
				smoketime = 8,
				smokesize = 4.2,
				smokecolor = 1.0,
				smokeTrailCastShadow = false,
				castshadow = false,
				startvelocity = 150,
				soundhit = "rockhit3",
				soundhitwet = "splssml",
				soundstart = "rocklit1",
				soundtrigger = true,
				startvelocity = 400,
				texture1 = "null",
				texture2 = "smoketrailaa",
				tolerance = 9950,
				tracks = true,
				trajectoryHeight = 1,
				turnrate = 52000,
				weaponacceleration = 500,
				weapontype = "StarburstLauncher",
				weapontimer = 0.32,
				weaponvelocity = 1200,
				damage = {
					default = 2600,
				},
			},
},
		weapons = {
			[1] = {
				def = "OMISSILES",
				maindir = "-1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[2] = {
				def = "OMISSILES",
				maindir = "1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[3] = {
				def = "SEMIAUTO",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[4] = {
				def = "SEMIAUTO",
				maindir = "-1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[5] = {
				def = "SEMIAUTO",
				maindir = "1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[6] = {
				def = "SEMIAUTO",
				maindir = "1 0 0",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
corohunter = {
weapondefs = {
corviper_missile = {
				areaofeffect = 50,
				avoidfeature = false,
				avoidfriendly = false,
				castshadow = false,
				cegtag = "missiletrailviper",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				firestarter = 70,
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile3fast.s3o",
				name = "Anti Orbital and Air Rocket Battery.",
				noselfdamage = true,
				range = 600,
				reloadtime = 0.5,
				smokecolor = 0.8,
				smokeperiod = 10,
				smokesize = 10,
				smoketime = 33,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				startvelocity = 900,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 65000,
				tracks = true,
				turnrate = 10000,
				turret = true,
				weaponacceleration = 400,
				weapontimer = 0.1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1300,
				cylindertargeting = 0.5,
				damage = {
					default = 200,
				},
			},
},
		weapons = {
			[1] = {
				def = "CORVIPER_MISSILE",
				onlytargetcategory = "SPACENOTOBJECT",
				fastautoretargeting = true,
			},
		},
},
armohorizon = {
	weapondefs = {
		arm_botrail = {
				commandfire = true,
				accuracy = 1,
				areaofeffect = 150,
				avoidfeature = false,
				avoidfriendly = false,
				collidefriendly = false,
				craterareaofeffect = 116,
				craterboost = 0.1,
				cratermult = 0.1,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:botrailspawn",
				gravityaffected = "true",
				heightboostfactor = 0,
				impulsefactor = 0.5,
				energypershot = 71000,
				metalpershot = 3300,
				model = "pbr_cube.s3o",
				name = "Orbital Vanguard Deployment Cannon",
				noselfdamage = true,
				range = 2000,
				reloadtime = 1,
				stockpile = true,
				stockpiletime = 60,
				soundhit = "xplonuk1xs",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundstartvolume = 50,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 500,
				hightrajectory = 1,
				stages = 24,
				interceptedByShieldType = 1,
				customparams = {
					spawns_name = "armvang",
					spawns_surface = "LAND",
					stockpilelimit = 2,
				},
				damage = {
					default = 1000,
				},
			},
		waterballon = {
				canattackground = false,
				range = 1000,
				reloadtime = 5,
				burnblow = false,
				name = "Orbital Strike Rocket",
				cegtag = "missiletrailviper",
				weapontype = "MissileLauncher",
				turnrate = 10000,
				weaponacceleration = 150,
				weaponvelocity = 800,
				weapontimer = 1,
				flighttime = 5,
				cylindertargeting = 0.4,
				damage = {
					commanders = nil,
					default = 1000,
					subs = nil,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "",
				def = "waterballon",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[2] = {
				def = "ARM_BOTRAIL",
				onlytargetcategory = "SURFACE",
			},
			[3] = {
				def = "NUCLEAR_LAUNCH",
			},
		},
},
armoplane = {
   weapondefs = {
      			space_rocket = {
				burst = 2,
				burstrate = 0.3,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Anti Space Rockets",
				noselfdamage = true,
				range = 410,
				reloadtime = 1,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				tolerance = 12000,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "MissileLauncher",
				startVelocity = 700,
				weaponVelocity = 700,
				canAttackGround = false,
				damage = {
					default = 40,
				},
			},
   },
		weapons = {
			[1] = {
				def = "SPACE_ROCKET",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
coroplane = {
  weapondefs = {
      			space_rocket = {
				burst = 2,
				burstrate = 0.3,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Anti Space Rockets",
				noselfdamage = true,
				range = 410,
				reloadtime = 1,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				tolerance = 12000,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "MissileLauncher",
				startVelocity = 700,
				weaponVelocity = 700,
				canAttackGround = false,
				damage = {
					default = 40,
				},
			},
   },
		weapons = {
			[1] = {
				def = "SPACE_ROCKET",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legoplane = {
   weapondefs = {
      			space_rocket = {
				burst = 2,
				burstrate = 0.3,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Anti Space Rockets",
				noselfdamage = true,
				range = 410,
				reloadtime = 1,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				tolerance = 12000,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "MissileLauncher",
				startVelocity = 700,
				weaponVelocity = 700,
				canAttackGround = false,
				damage = {
					default = 40,
				},
			},
   },
		weapons = {
			[1] = {
				def = "SPACE_ROCKET",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
}