-- Space Defense Weapons
-- Space Expansion V2.9
-- Authors: RandomGuy
-- https://github.com/nuttyb-community/nuttyb

{
armomulti = {
weapondefs = {
			Orbital_cannon = {
				areaofeffect = 100,
				alwaysvisible = true,
				avoidfriendly = false,
				avoidfeature = false,
				canattackground = true,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.3,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 5,
				impulsefactor = 0.2,
				name = "Orbital Gauss Cannon",
				noselfdamage = true,
				range = 600,
				reloadtime = 1,
				predictboost = 1,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "cannhvy2",
				turret = true,
				weapontimer = 3,
				weapontype = "Cannon",
				weaponvelocity = 1200,
				heightBoostFactor = 0,
				damage = {
					default = 400,
				},
			},
Orbital_HighEnergyLaser = {
				areaofeffect = 10,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				beamtime = 0.15,
				corethickness = 0.18,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				edgeeffectiveness = 0.15,
				energypershot = 20,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7.7,
				name = "HighEnergyLaser",
				noselfdamage = true,
				range = 1200,
				reloadtime = 3,
				rgbcolor = "0 1 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 2.4,
				tolerance = 65000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 900,
				heightmod = 0.1,
				cylindertargeting = 50,
				minIntensity = 1,
				damage = {
					default = 450,
		},
},
},
		weapons = {
[1] = {
				def = "ORBITAL_HIGHENERGYLASER",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
},
[2] = {
				def = "ORBITAL_HIGHENERGYLASER",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
},
[3] = {
				def = "ORBITAL_CANNON",
				fastautoretargeting = true,
				onlytargetcategory = "NOTAIR",
			},
		},
},
coromulti = {
weapondefs = {
			corviper_missile = {
				areaofeffect = 50,
				avoidfeature = false,
				avoidfriendly = false,
				castshadow = true,
				cegtag = "missiletrailviper",
				alwaysvisible = true,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = true,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				firestarter = 70,
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile3fast.s3o",
				name = "Heavy o2g rocket launcher",
				noselfdamage = true,
				range = 600,
				reloadtime = 2,
				smokecolor = 0.8,
				smokeperiod = 10,
				smokesize = 10,
				smoketime = 33,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				startvelocity = 900,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 65000,
				tracks = true,
				turnrate = 6000,
				turret = true,
				weaponacceleration = 400,
				weapontimer = 0.1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1300,
				cylindertargeting = 10,
				heightmod = 0.1,
				damage = {
					default = 820,
				},
			},
			doomsday_green_laser = {
				areaofeffect = 8,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				beamtime = 0.225,
				corethickness = 0.185,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				edgeeffectiveness = 0.15,
				energypershot = 45,
				explosiongenerator = "custom:laserhit-medium-red",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7.7,
				name = "High energy laser",
				noselfdamage = true,
				range = 1200,
				reloadtime = 6,
				rgbcolor = "1 0.1 0.1",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 5,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 900,
				heightmod = 0.1,
				cylindertargeting = 50,
				minIntensity = 1,
				damage = {
					default = 1000,
				},
			},
			doomsday_red_laser = {
				areaofeffect = 40,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				cegtag = "missiletrailsmall",
				flighttime = 4,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 100,
				impulsefactor = 0,
				model = "cormissile3fast.s3o",
				name = "Rocket Battery",
				noselfdamage = true,
				proximitypriority = 1,
				range = 900,
				reloadtime = 0.8,
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasrfir3",
				soundtrigger = 1,
				startvelocity = 600,
				tolerance = 10000,
				turnrate = 20000,
				turret = true,
				tracks = true,
				weapontype = "MissileLauncher",
				weaponvelocity = 600,
				damage = {
					default = 80,
				},
			},
		},
		weapons = {
			[1] = {
				def = "CORVIPER_MISSILE",
				onlytargetcategory = "NOTAIR",
			},
			[2] = {
				def = "DOOMSDAY_GREEN_LASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[3] = {
				def = "DOOMSDAY_RED_LASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
legomulti = {
		weapondefs = {
			Orbital_Gatling = {
				accuracy = 0,
				areaofeffect = 32,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				burst = 3,
				burstrate = 0.02,
				burnblow = false,
				canattackground = false,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 192,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 3,
				duration = 0.1,
				edgeeffectiveness = 1,
				gravityaffected = "false",
				impulsefactor = 0,
				mygravity = 0.01,
				name = "Heavy Anti-Orbital Gatling Gun",
				noselfdamage = true,
				predictboost = 1,
				range = 1100,
				reloadtime = 0.166,
				smoketrail = false,
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "minigun3",
				soundhitvolume = 7.5,
				soundstartvolume = 5,
				stages = 0,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3,
				tolerance = 16000,
				turret = true,
				weapontimer = 3,
				weapontype = "LaserCannon",
				weaponvelocity = 3642,
				damage = {
					default = 15.5,
				},
				rgbcolor = "1 0.33 0.7",
				explosiongenerator = "custom:plasmahit-sparkonly",
				ownerExpAccWeight = 1.35,--does this affect sprayangle too?
				sprayangle = 100,
				fallOffRate = 0.2,
			},
			orbital_railgun = {
				areaofeffect = 16,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				canattackground = true,
				collidefriendly = false,
				collidefeature = false,
				cylindertargeting = 50,
				heightMod = 0.1,
				burnblow = false,
				cegtag = "railgun",
				collisionSize = 0.667,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.12,
				edgeeffectiveness = 0.85,
				energypershot = 200,
				explosiongenerator = "custom:plasmahit-sparkonly",
				firestarter = 0,
				hardstop = true,
				impactonly = true,
				impulsefactor = 1,
				intensity = 0.8,
				name = "Orbital Railgun",
				noexplode = true,
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				predictboost = 1,
				range = 850,
				reloadtime = 6,
				rgbcolor = "0.34 0.64 0.94",
				soundhit = "mavgun3",
				soundhitwet = "splshbig",
				soundstart = "heavyrailgun",
				soundstartvolume = 26,
				thickness = 3,
				tolerance = 65000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 3180,
				damage = {
					default = 2400,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_GATLING",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				burstControlWhenOutOfArc = "nil",
			},
			[2] = {
				def = "ORBITAL_RAILGUN",
				onlytargetcategory = "SURFACE",
				burstControlWhenOutOfArc = "nil",
				slaveto = "nil",
			},
		},
},
legobomber = {
weapondefs = {
shocker_low = {
				areaofeffect = 200,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "starfire_arty",
				collidefriendly = false,
				craterareaofeffect = 200,
				craterboost = 0,
				cratermult = 0,
				size = 6,
				edgeeffectiveness = 0.2,
				energypershot = 300,
				explosiongenerator = "custom:starfire-explosion",
				gravityaffected = "true",
				heightboostfactor = 0,
				impulsefactor = 0.5,
				leadbonus = 0,
				name = "Long-Range Heavy Cluster Plasma Cannon",
				noselfdamage = true,
				range = 1000,
				reloadtime = 5,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "lrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundhitvolume = 38,
				soundstartvolume = 24,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 600,
				customparams = {
					cluster_def = 'cluster_munition',
					cluster_number = 4,
				},
				damage = {
					default = 2000,
					shields = 1000,
					commanders = 666.6,
				},
			},
cluster_munition = {
				areaofeffect = 150,
				avoidfeature = false,
				cegtag = "ministarfire",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:ministarfire-explosion",
				gravityaffected = "true",
				impulsefactor = 0.5,
				name = "Plasma Burst",
				noselfdamage = true,
				maxvelocity = 720,
				range = 110,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "xplomed2",
				soundhitwet = "splsmed",
				soundstart = "cannhvy5",
				weapontype = "Cannon",
				reloadtime = 5,
				damage = {
					default = 500,
				},
			},
		},
		weapons = {
			[1] = {
				def = "SHOCKER_LOW",
				maindir = "0 -1 0",
				onlytargetcategory = "SURFACE",
			},
		},
},
armollt = {
	weapondefs = {
			arm_lightlaser = {
				range = 600,
				reloadtime = 0.7,
				minIntensity = 1,
				cylindertargeting = 50,
				heightmod = 0.1,
				damage = {
					commanders = nil,
					default = 42,
					subs = nil,
					vtol = nil,
				},
               },
        },
weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
corollt = {
	weapondefs = {
			cor_lightlaser = {
				range = 600,
				reloadtime = 0.7,
				minIntensity = 1,
				cylindertargeting = 50,
				heightmod = 0.1,
				damage = {
					commanders = nil,
					default = 42,
					subs = nil,
					vtol = nil,
				},
               },
        },
weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
legollt = {
	weapondefs = {
			heat_ray = {
				range = 600,
				reloadtime = 0.7,
				minIntensity = 1,
				beamtime = 0.12,
				cylindertargeting = 50,
				heightmod = 0.1,
				damage = {
					commanders = nil,
					default = 42,
					subs = nil,
					vtol = nil,
				},
               },
        },
weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
}