-- Armada Space Weapons
-- Space Expansion V2.9
-- Authors: RandomGuy
-- https://github.com/nuttyb-community/nuttyb

{
armspace ={
buildoptions = {
"armoc",
"armosat",
"armofighter",
"armocan",
"armosolar",
"armobruiser",
"armotachyon",
},
},
armspacet3 = {
buildoptions = {
"armoc",
"armobomber",
"armohorizon",
"armokaiser",
"armoliberator",
},
},
armofighter = {
weapondefs = {
			lightlaser = {
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "0.05 0.05 1",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 220,
				damage = {
					default = 17.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armocan = {
weapondefs = {
			Orbital_Cannon = {
				areaofeffect = 300,
				avoidfeature = false,
				avoidfriendly = false,      
				craterareaofeffect = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = true,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 10,
				impulsefactor = 1,
				name = "Orbital Bombardment",
				tolerance = 65000,
				noselfdamage = true,
				range = 100,
				reloadtime = 10,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "KroGun1",
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 500,
					commanders = 166.6,
					shields = 100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_CANNON",
				maindir = "0 -1 0",
				onlytargetcategory = "SURFACE",
			},
		},
},
armorocket = {
weapondefs = {
			orbital_rocket = {
				areaofeffect = 250,
				alwaysvisible = true,
				canattackground = false,
				collideenemy = true,
				cegtag = "cruisemissiletrail-tacnuke",
				cylindertargeting = 1,
				energypershot = 0,
				explosiongenerator = "custom:newnuketac",
				firestarter = 10,
				impulsefactor = 1.1,
				name = "Orbital Rocket System",
				range = 1350,
				reloadtime = 7.5,
				model = "cortronmissile.s3o",
				stockpile = false,
				soundhit = "xplomed4",
				soundstart = "mismed1",
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 4,
				startvelocity = 200,
				tracks = true,
				tolerance = 40000,
				turnrate = 40000,
				weaponacceleration = 1000,
				weapontimer = 1,
				weapontype = "StarburstLauncher",
				weaponvelocity = 2000,
				waterweapon = true,
				firesubmersed = true,
				damage = {
					default = 1,
					space = 2600,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_ROCKET",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armobruiser = {
weapondefs = {
			space_emg = {
				collidefriendly = false,
				collidefeature = false,
				accuracy = 0,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				duration = 0.05,
				edgeeffectiveness = 0.5,
				energypershot = 2,
				explosiongenerator = "custom:genericshellexplosion-small",
				impulsefactor = 0,
				intensity = 5,
				name = "Space Laser Battery",
				noselfdamage = true,
				proximitypriority = 1,
				range = 700,
				reloadtime = 0.5,
				rgbcolor = "0.05 0.05 1",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				thickness = 5,
				tolerance = 40000,
				turret = true,
				weapontimer = 1,
				weapontype = "LaserCannon",
				weaponvelocity = 2400,
				cylindertargeting = 0.5,
				damage = {
					default = 75,
				},
			},
		},
		weapons = {
			[1] = {
				def = "SPACE_EMG",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
				maxangledif = 360,
			},
			[2] = {
				def = "SPACE_EMG",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
				maxangledif = 360,
			},
		},
},
armotachyon = {
weapondefs = {
oata = {
				areaofeffect = 16,
				avoidfeature = false,
				collidefriendly = false,
				avoidfriendly = false,
				canattackground = false,
				beamtime = 0.1,
				corethickness = 0.3,
				largebeamlaser = true,
				laserflaresize = 6.5,
				noselfdamage = true,
				explosiongenerator = "custom:laserhit-large-blue",
				name = "Orbital 2 orbital tachyon lance.",
				rgbcolor = "0 0 1",
				scrollspeed = 5,
				soundhitwet = "sizzle",
				soundstart = "annigun1",
				soundtrigger = 1,
				texture3 = "largebeam",
				thickness = 4.5,
				tilelength = 150,
				range = 1200,
				reloadtime = 7,
				minIntensity = 1,
				energypershot = 200,
				weapontype = "BeamLaser",
				tolerance = 10000,
				turret = true,
				weaponvelocity = 1400,
				cylindertargeting = 30,
				damage = {
					default = 1550,
				},
			},
		},
		weapons = {
			[1] = {
				def = "OATA",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
			[2] = {
				def = "",
				onlytargetcategory = "",
			},
		},
},
armokaiser = {
weapondefs = {
			plasma = {
				range = 1000,
				heightBoostFactor = 0,
				customparams = {
					engagementrange = 1200,
					carried_unit = "armodrone",     --Name of the unit spawned by this carrier unit.
					spawns_surface = "LAND SEA",
				},
			},
			aamissile = {
				avoidfriendly = false,
				collidefriendly = false,
				burst = 2,
				burstrate = 0.8,
				areaofeffect = 100,
				burnblow = false,
				cegtag = "missiletrailaa",
				collidefeature = false,
				flighttime = 5,
				name = "Battleship Missile",
				range = 1000,
				weaponacceleration = 300,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1200,
				cylindertargeting = 0.4,
				damage = {
					default = 1000,
					vtol = "500",
				},
			},
		},
		weapons = {
			[1] = {
				def = "AAMISSILE",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[2] = {
				def = "PLASMA",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armodrone = {
weapondefs = {
armodrone_missile = {
				areaofeffect = 40,
				avoidfeature = false,
				burnblow = false,
				canattackground = false,
				cegtag = "missiletrailsmall-red",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-catapult",
				firestarter = 70,
				flighttime = 9,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "catapultmissile.s3o",
				name = "Seeking Interplanetary Missile Launcher",
				noselfdamage = true,
				range = 500,
				reloadtime = 0.3,
				smoketrail = true,
				smokePeriod = 7,
				smoketime = 13,
				smokesize = 5.4,
				smokecolor = 0.95,
				smokeTrailCastShadow = false,
				castshadow = false,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "rockhvy2",
				startvelocity = 800,
				texture1 = "null",
				texture2 = "smoketrailaa3",
				tolerance = 20000,
				tracks = true,
				turnrate = 50000,
				turret = true,
				weaponacceleration = 500,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1200,
				cylindertargeting = 0.4,
				damage = {
					default = 9,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ARMODRONE_MISSILE",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armoliberator = {
weapondefs = {
			heavyplasma = {
				alwaysVisible = true,
				accuracy = 100,
				areaofeffect = 200,
				collidefriendly = false,
				collidefeature = false,
				hightrajectory = 1,
				range = 2100,
				heightBoostFactor = 0,
				damage = {
					default = 400,
					shields = 200,
				},
			},
			ferret_missile = {
				areaofeffect = 50,
				collidefriendly = false,
				collidefeature = false,
				burnblow = false,
				edgeeffectiveness = 0.15,
				flighttime = 5,
				name = "Pop-up rapid-fire o2a missile launcher",
				range = 1000,
				reloadtime = 2,
				damage = {
					default = 600,
				},
			},
		},
		weapons = {
			[2] = {
				def = "HEAVYPLASMA",
				maindir = "0 0 1",
				maxangledif = 320,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[4] = {
				def = "HEAVYPLASMA",
				maindir = "-4 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[5] = {
				def = "HEAVYPLASMA",
				maindir = "4 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[6] = {
				maindir = "0 -1 -2",
				maxangledif = 270,
				def = "FERRET_MISSILE",
				onlytargetcategory = "VTOL SPACENOTOBJECT",
			},
			[7] = {
				def = "FERRET_MISSILE",
				onlytargetcategory = "VTOL SPACENOTOBJECT",
			},
		},
},
corspace = {
buildoptions = {
"corosat",
"coroc",
"corosolar",
"corofighter",
"corocan",
"corobruiser",
"coroheavy",
},
},
corspacet3 = {
buildoptions = {
"coroc",
"corobomber",
"corohunter",
"coroheatray",
"coroapoc",
},
},
coroheatray ={
weapondefs = {
			laser = {
				avoidneutral = false,
				collideneutral = false,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				areaofeffect = 72,
				avoidfriendly = false,
				energypershot = 350,
				range = 1200,
				minIntensity = 1,
				cylindertargeting = 10,
				heightmod = 0.1,
				damage = {
					default = 4000,
				},
			},
		},
		weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
			[2] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
		},
},
corofighter = {
weapondefs = {
			lightlaser = {
				canattackground = false,
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "1 0.05 0.05",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 100,
				damage = {
					default = 17.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
}
